AllCops:
  NewCops: enable
  Exclude: 
    - 'bin/**/*'
    - 'db/**/*'

Style/OpenStructUse:
  Enabled: false

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'

Metrics/BlockLength:
  AllowedMethods:
    - describe
    - context
    - let

Metrics/MethodLength:
  Max: 15
